import {useEffect, useState} from 'react'
import logo from './logo.svg'
import style from './index.module.css'
import {EditOutlined, EllipsisOutlined, SettingOutlined} from '@ant-design/icons';
import {Avatar, Card} from 'antd';

import Table from '../../components/table2'
import {Button, Drawer} from 'antd';
import PouchDB from 'pouchdb';
import 'antd/dist/antd.css'

const {Meta} = Card;

function TreeCalc(node: any) {

    if (node.children) {
        let sum = {
            "enero2022": 0,
            "febrero2022": 0,
            "marzo2022": 0,
            "abril2022": 0,
            "mayo2022": 0,
            "junio2022": 0,
            "julio2022": 0,
            "agosto2022": 0,
            "setiembre2022": 0,
            "octubre2022": 0,
            "noviembre2022": 0,
            "diciembre2022": 0,

            "enero2023": 0,
            "febrero2023": 0,
            "marzo2023": 0,
            "abril2023": 0,
            "mayo2023": 0,
            "junio2023": 0,
            "julio2023": 0,
            "agosto2023": 0,
            "setiembre2023": 0,
            "octubre2023": 0,
            "noviembre2023": 0,
            "diciembre2023": 0,

            "enero2024": 0,
            "febrero2024": 0,
            "marzo2024": 0,
            "abril2024": 0,
            "mayo2024": 0,
            "junio2024": 0,
            "julio2024": 0,
            "agosto2024": 0,
            "setiembre2024": 0,
            "octubre2024": 0,
            "noviembre2024": 0,
            "diciembre2024": 0,
        }
        for (let i=0; i<node.children.length; i++) {
            sum.enero2022 += TreeCalc(node.children[i]).enero2022
            sum.febrero2022 += TreeCalc(node.children[i]).febrero2022
            sum.marzo2022 += TreeCalc(node.children[i]).marzo2022
            sum.abril2022 += TreeCalc(node.children[i]).abril2022
            sum.mayo2022 += TreeCalc(node.children[i]).mayo2022
            sum.junio2022 += TreeCalc(node.children[i]).junio2022
            sum.julio2022 += TreeCalc(node.children[i]).julio2022
            sum.agosto2022 += TreeCalc(node.children[i]).agosto2022
            sum.setiembre2022 += TreeCalc(node.children[i]).setiembre2022
            sum.octubre2022 += TreeCalc(node.children[i]).octubre2022
            sum.enero2022 += TreeCalc(node.children[i]).enero2022
            sum.diciembre2022 += TreeCalc(node.children[i]).diciembre2022

            sum.enero2023 += TreeCalc(node.children[i]).enero2023
            sum.febrero2023 += TreeCalc(node.children[i]).febrero2023
            sum.marzo2023 += TreeCalc(node.children[i]).marzo2023
            sum.abril2023 += TreeCalc(node.children[i]).abril2023
            sum.mayo2023 += TreeCalc(node.children[i]).mayo2023
            sum.junio2023 += TreeCalc(node.children[i]).junio2023
            sum.julio2023 += TreeCalc(node.children[i]).julio2023
            sum.agosto2023 += TreeCalc(node.children[i]).agosto2023
            sum.setiembre2023 += TreeCalc(node.children[i]).setiembre2023
            sum.octubre2023 += TreeCalc(node.children[i]).octubre2023
            sum.enero2023 += TreeCalc(node.children[i]).enero2023
            sum.diciembre2023 += TreeCalc(node.children[i]).diciembre2023

            sum.enero2024 += TreeCalc(node.children[i]).enero2024
            sum.febrero2024 += TreeCalc(node.children[i]).febrero2024
            sum.marzo2024 += TreeCalc(node.children[i]).marzo2024
            sum.abril2024 += TreeCalc(node.children[i]).abril2024
            sum.mayo2024 += TreeCalc(node.children[i]).mayo2024
            sum.junio2024 += TreeCalc(node.children[i]).junio2024
            sum.julio2024 += TreeCalc(node.children[i]).julio2024
            sum.agosto2024 += TreeCalc(node.children[i]).agosto2024
            sum.setiembre2024 += TreeCalc(node.children[i]).setiembre2024
            sum.octubre2024 += TreeCalc(node.children[i]).octubre2024
            sum.enero2024 += TreeCalc(node.children[i]).enero2024
            sum.diciembre2024 += TreeCalc(node.children[i]).diciembre2024
        }
        node.enero2022 = sum.enero2022;
        node.febrero2022= sum.febrero2022;
        node.marzo2022 = sum.marzo2022;
        node.abril2022 = sum.abril2022;
        node.mayo2022 = sum.mayo2022;
        node.junio2022 = sum.junio2022;
        node.julio2022 = sum.julio2022;
        node.agosto2022= sum.agosto2022;
        node.setiembre2022 = sum.setiembre2022;
        node.octubre2022 = sum.octubre2022;
        node.noviembre2022 = sum.noviembre2022;
        node.diciembre2022 = sum.diciembre2022;

        node.enero2023 = sum.enero2023;
        node.febrero2023= sum.febrero2023;
        node.marzo2023 = sum.marzo2023;
        node.abril2023 = sum.abril2023;
        node.mayo2023 = sum.mayo2023;
        node.junio2023 = sum.junio2023;
        node.julio2023 = sum.julio2023;
        node.agosto2023= sum.agosto2023;
        node.setiembre2023 = sum.setiembre2023;
        node.octubre2023 = sum.octubre2023;
        node.noviembre2023 = sum.noviembre2023;
        node.diciembre2023 = sum.diciembre2023;

        node.enero2024 = sum.enero2024;
        node.febrero2024= sum.febrero2024;
        node.marzo2024 = sum.marzo2024;
        node.abril2024 = sum.abril2024;
        node.mayo2024 = sum.mayo2024;
        node.junio2024 = sum.junio2024;
        node.julio2024 = sum.julio2024;
        node.agosto2024= sum.agosto2024;
        node.setiembre2024 = sum.setiembre2024;
        node.octubre2024 = sum.octubre2024;
        node.noviembre2024 = sum.noviembre2024;
        node.diciembre2024 = sum.diciembre2024;

        return sum;
    }
    else {
        return {
            "enero2022": (isNaN(node.enero2022) || node.enero2022 == "" || node.enero2022 == undefined)?0:parseInt(node.enero2022) ,
            "febrero2022": (isNaN(node.febrero2022) || node.febrero2022 == "" || node.febrero2022 == undefined)?0:parseInt(node.febrero2022) ,
            "marzo2022": (isNaN(node.marzo2022) || node.marzo2022 == "" || node.marzo2022 == undefined)?0:parseInt(node.marzo2022) ,
            "abril2022": (isNaN(node.abril2022) || node.abril2022 == "" || node.abril2022 == undefined)?0:parseInt(node.abril2022) ,
            "mayo2022": (isNaN(node.mayo2022) || node.mayo2022 == "" || node.mayo2022 == undefined)?0:parseInt(node.mayo2022) ,
            "junio2022": (isNaN(node.junio2022) || node.junio2022 == "" || node.junio2022 == undefined)?0:parseInt(node.junio2022) ,
            "julio2022": (isNaN(node.julio2022) || node.julio2022 == "" || node.julio2022 == undefined)?0:parseInt(node.julio2022) ,
            "agosto2022": (isNaN(node.agosto2022) || node.agosto2022 == "" || node.agosto2022 == undefined)?0:parseInt(node.agosto2022) ,
            "setiembre2022": (isNaN(node.setiembre2022) || node.setiembre2022 == "" || node.setiembre2022 == undefined)?0:parseInt(node.setiembre2022) ,
            "octubre2022": (isNaN(node.octubre2022) || node.octubre2022 == "" || node.octubre2022 == undefined)?0:parseInt(node.octubre2022) ,
            "noviembre2022": (isNaN(node.noviembre2022) || node.noviembre2022 == "" || node.noviembre2022 == undefined)?0:parseInt(node.noviembre2022) ,
            "diciembre2022":(isNaN(node.diciembre2022) || node.diciembre2022 == "" || node.diciembre2022 == undefined)?0:parseInt(node.diciembre2022) ,

            "enero2023": (isNaN(node.enero2023) || node.enero2023 == "" || node.enero2023 == undefined)?0:parseInt(node.enero2023) ,
            "febrero2023": (isNaN(node.febrero2023) || node.febrero2023 == "" || node.febrero2023 == undefined)?0:parseInt(node.febrero2023) ,
            "marzo2023": (isNaN(node.marzo2023) || node.marzo2023 == "" || node.marzo2023 == undefined)?0:parseInt(node.marzo2023) ,
            "abril2023": (isNaN(node.abril2023) || node.abril2023 == "" || node.abril2023 == undefined)?0:parseInt(node.abril2023) ,
            "mayo2023": (isNaN(node.mayo2023) || node.mayo2023 == "" || node.mayo2023 == undefined)?0:parseInt(node.mayo2023) ,
            "junio2023": (isNaN(node.junio2023) || node.junio2023 == "" || node.junio2023 == undefined)?0:parseInt(node.junio2023) ,
            "julio2023": (isNaN(node.julio2023) || node.julio2023 == "" || node.julio2023 == undefined)?0:parseInt(node.julio2023) ,
            "agosto2023": (isNaN(node.agosto2023) || node.agosto2023 == "" || node.agosto2023 == undefined)?0:parseInt(node.agosto2023) ,
            "setiembre2023": (isNaN(node.setiembre2023) || node.setiembre2023 == "" || node.setiembre2023 == undefined)?0:parseInt(node.setiembre2023) ,
            "octubre2023": (isNaN(node.octubre2023) || node.octubre2023 == "" || node.octubre2023 == undefined)?0:parseInt(node.octubre2023) ,
            "noviembre2023": (isNaN(node.noviembre2023) || node.noviembre2023 == "" || node.noviembre2023 == undefined)?0:parseInt(node.noviembre2023) ,
            "diciembre2023":(isNaN(node.diciembre2023) || node.diciembre2023 == "" || node.diciembre2023 == undefined)?0:parseInt(node.diciembre2023) ,

            "enero2024": (isNaN(node.enero2024) || node.enero2024 == "" || node.enero2024 == undefined)?0:parseInt(node.enero2024) ,
            "febrero2024": (isNaN(node.febrero2024) || node.febrero2024 == "" || node.febrero2024 == undefined)?0:parseInt(node.febrero2024) ,
            "marzo2024": (isNaN(node.marzo2024) || node.marzo2024 == "" || node.marzo2024 == undefined)?0:parseInt(node.marzo2024) ,
            "abril2024": (isNaN(node.abril2024) || node.abril2024 == "" || node.abril2024 == undefined)?0:parseInt(node.abril2024) ,
            "mayo2024": (isNaN(node.mayo2024) || node.mayo2024 == "" || node.mayo2024 == undefined)?0:parseInt(node.mayo2024) ,
            "junio2024": (isNaN(node.junio2024) || node.junio2024 == "" || node.junio2024 == undefined)?0:parseInt(node.junio2024) ,
            "julio2024": (isNaN(node.julio2024) || node.julio2024 == "" || node.julio2024 == undefined)?0:parseInt(node.julio2024) ,
            "agosto2024": (isNaN(node.agosto2024) || node.agosto2024 == "" || node.agosto2024 == undefined)?0:parseInt(node.agosto2024) ,
            "setiembre2024": (isNaN(node.setiembre2024) || node.setiembre2024 == "" || node.setiembre2024 == undefined)?0:parseInt(node.setiembre2024) ,
            "octubre2024": (isNaN(node.octubre2024) || node.octubre2024 == "" || node.octubre2024 == undefined)?0:parseInt(node.octubre2024) ,
            "noviembre2024": (isNaN(node.noviembre2024) || node.noviembre2024 == "" || node.noviembre2024 == undefined)?0:parseInt(node.noviembre2024) ,
            "diciembre2024":(isNaN(node.diciembre2024) || node.diciembre2024 == "" || node.diciembre2024 == undefined)?0:parseInt(node.diciembre2024) ,
        }
        //if (isNaN(node.enero2022) || node.enero2022 == "") return 0
        //return parseInt(node.enero2022)
    }
}

function TreeCalc2(node: any) {

    if (node.children) {
        let sum = {
            "xenero2022": 0,
            "xfebrero2022": 0,
            "xmarzo2022": 0,
            "xabril2022": 0,
            "xmayo2022": 0,

        }
        for (let i=0; i<node.children.length; i++) {
            sum.xenero2022 += TreeCalc2(node.children[i]).xenero2022
            sum.xfebrero2022 += TreeCalc2(node.children[i]).xfebrero2022
            sum.xmarzo2022 += TreeCalc2(node.children[i]).xmarzo2022
            sum.xabril2022 += TreeCalc2(node.children[i]).xabril2022
            sum.xmayo2022 += TreeCalc2(node.children[i]).xmayo2022
        }
        node.xenero2022 = sum.xenero2022;
        node.xfebrero2022= sum.xfebrero2022;
        node.xmarzo2022 = sum.xmarzo2022;
        node.xabril2022 = sum.xabril2022;
        node.xmayo2022 = sum.xmayo2022;


        return sum;
    }
    else {
        return {
            "xenero2022": (isNaN(node.xenero2022) || node.xenero2022 == "" || node.xenero2022 == undefined)?0:parseInt(node.xenero2022) ,
            "xfebrero2022": (isNaN(node.xfebrero2022) || node.xfebrero2022 == "" || node.xfebrero2022 == undefined)?0:parseInt(node.xfebrero2022) ,
            "xmarzo2022": (isNaN(node.xmarzo2022) || node.xmarzo2022 == "" || node.xmarzo2022 == undefined)?0:parseInt(node.xmarzo2022) ,
            "xabril2022": (isNaN(node.xabril2022) || node.xabril2022 == "" || node.xabril2022 == undefined)?0:parseInt(node.xabril2022) ,
            "xmayo2022": (isNaN(node.xmayo2022) || node.xmayo2022 == "" || node.xmayo2022 == undefined)?0:parseInt(node.xmayo2022) ,
        }
        //if (isNaN(node.xenero2022) || node.xenero2022 == "") return 0
        //return parseInt(node.xenero2022)
    }
}


function Component() {
    const [visible, setVisible] = useState(false);
    const [data, setData] = useState([])

    let db = new PouchDB('poi_database');

    const NewData = [
        {
            "key": "1",
            "indice": "1",
            "nombre": "OBJETIVO INSTITUCIONAL PERMANENTE 1 (OBIP 1): ASEGURAR UNA FORMACIÓN ACADÉMICA DE CALIDAD",
            "responsable": "",
            "um": "",
            "meta": "",
            "enero2022": 648,
            "febrero2022": 79,
            "marzo2022": 80,
            "abril2022": 80,
            "mayo2022": 80,
            "junio2022": 80,
            "julio2022": 92,
            "agosto2022": 68,
            "setiembre2022": 80,
            "octubre2022": 80,
            "noviembre2022": 0,
            "diciembre2022": 91,
            "enero2023": 744,
            "febrero2023": 91,
            "marzo2023": 80,
            "abril2023": 80,
            "mayo2023": 80,
            "junio2023": 80,
            "julio2023": 92,
            "agosto2023": 80,
            "setiembre2023": 80,
            "octubre2023": 80,
            "noviembre2023": 0,
            "diciembre2023": 79,
            "enero2024": 744,
            "febrero2024": 91,
            "marzo2024": 80,
            "abril2024": 80,
            "mayo2024": 80,
            "junio2024": 80,
            "julio2024": 92,
            "agosto2024": 80,
            "setiembre2024": 80,
            "octubre2024": 80,
            "noviembre2024": 0,
            "diciembre2024": 79,
            "xenero2022": "",
            "xfebrero2022": "",
            "xmarzo2022": "",
            "xabril2022": "",
            "xmayo2022": 60,
            "xjunio2022": "",
            "xjulio2022": "",
            "xagosto2022": "",
            "xsetiembre2022": "",
            "xoctubre2022": "",
            "xnoviembre2022": "",
            "xdiciembre2022": "",
            "xenero2023": "",
            "xfebrero2023": "",
            "xmarzo2023": "",
            "xabril2023": "",
            "xmayo2023": "",
            "xjunio2023": "",
            "xjulio2023": "",
            "xagosto2023": "",
            "xsetiembre2023": "",
            "xoctubre2023": "",
            "xnoviembre2023": "",
            "xdiciembre2023": "",
            "xenero2024": "",
            "xfebrero2024": "",
            "xmarzo2024": "",
            "xabril2024": "",
            "xmayo2024": "",
            "xjunio2024": "",
            "xjulio2024": "",
            "xagosto2024": "",
            "xsetiembre2024": "",
            "xoctubre2024": "",
            "xnoviembre2024": "",
            "xdiciembre2024": "",
            "ppto2022": "463",
            "ppto2023": "591",
            "ppto2024": "925",
            "children": [
                {
                    "key": "1.1",
                    "indice": "1.1",
                    "nombre": "Objetivo General de Mediano Plazo 1.1: Garantizar una formación académica de calidad en la Facultad de Ingeniería y Arquitectura",
                    "responsable": "",
                    "um": "",
                    "meta": "",
                    "enero2022": 124,
                    "febrero2022": 29,
                    "marzo2022": 30,
                    "abril2022": 30,
                    "mayo2022": 30,
                    "junio2022": 30,
                    "julio2022": 35,
                    "agosto2022": 25,
                    "setiembre2022": 30,
                    "octubre2022": 30,
                    "noviembre2022": 0,
                    "diciembre2022": 34,
                    "enero2023": 144,
                    "febrero2023": 34,
                    "marzo2023": 30,
                    "abril2023": 30,
                    "mayo2023": 30,
                    "junio2023": 30,
                    "julio2023": 35,
                    "agosto2023": 30,
                    "setiembre2023": 30,
                    "octubre2023": 30,
                    "noviembre2023": 0,
                    "diciembre2023": 29,
                    "enero2024": 144,
                    "febrero2024": 34,
                    "marzo2024": 30,
                    "abril2024": 30,
                    "mayo2024": 30,
                    "junio2024": 30,
                    "julio2024": 35,
                    "agosto2024": 30,
                    "setiembre2024": 30,
                    "octubre2024": 30,
                    "noviembre2024": 0,
                    "diciembre2024": 29,
                    "xenero2022": "",
                    "xfebrero2022": "",
                    "xmarzo2022": "",
                    "xabril2022": "",
                    "xmayo2022": 20,
                    "xjunio2022": "",
                    "xjulio2022": "",
                    "xagosto2022": "",
                    "xsetiembre2022": "",
                    "xoctubre2022": "",
                    "xnoviembre2022": "",
                    "xdiciembre2022": "",
                    "xenero2023": "",
                    "xfebrero2023": "",
                    "xmarzo2023": "",
                    "xabril2023": "",
                    "xmayo2023": "",
                    "xjunio2023": "",
                    "xjulio2023": "",
                    "xagosto2023": "",
                    "xsetiembre2023": "",
                    "xoctubre2023": "",
                    "xnoviembre2023": "",
                    "xdiciembre2023": "",
                    "xenero2024": "",
                    "xfebrero2024": "",
                    "xmarzo2024": "",
                    "xabril2024": "",
                    "xmayo2024": "",
                    "xjunio2024": "",
                    "xjulio2024": "",
                    "xagosto2024": "",
                    "xsetiembre2024": "",
                    "xoctubre2024": "",
                    "xnoviembre2024": "",
                    "xdiciembre2024": "",
                    "ppto2022": "135",
                    "ppto2023": "292",
                    "ppto2024": "270",
                    "children": [
                        {
                            "key": "1.1.1",
                            "indice": "1.1.1",
                            "nombre": "Objetivo Específico de Mediano Plazo 1.1.1: Garantizar la capacidad de gestión de la Facultad de Ingeniería y Arquitectura",
                            "responsable": "",
                            "um": "",
                            "meta": "",
                            "enero2022": 10,
                            "febrero2022": 5,
                            "marzo2022": 5,
                            "abril2022": 5,
                            "mayo2022": 5,
                            "junio2022": 5,
                            "julio2022": 5,
                            "agosto2022": 5,
                            "setiembre2022": 5,
                            "octubre2022": 5,
                            "noviembre2022": 0,
                            "diciembre2022": 5,
                            "enero2023": 10,
                            "febrero2023": 5,
                            "marzo2023": 5,
                            "abril2023": 5,
                            "mayo2023": 5,
                            "junio2023": 5,
                            "julio2023": 5,
                            "agosto2023": 5,
                            "setiembre2023": 5,
                            "octubre2023": 5,
                            "noviembre2023": 0,
                            "diciembre2023": 5,
                            "enero2024": 10,
                            "febrero2024": 5,
                            "marzo2024": 5,
                            "abril2024": 5,
                            "mayo2024": 5,
                            "junio2024": 5,
                            "julio2024": 5,
                            "agosto2024": 5,
                            "setiembre2024": 5,
                            "octubre2024": 5,
                            "noviembre2024": 0,
                            "diciembre2024": 5,
                            "xenero2022": "",
                            "xfebrero2022": "",
                            "xmarzo2022": "",
                            "xabril2022": "",
                            "xmayo2022": 3,
                            "xjunio2022": "",
                            "xjulio2022": "",
                            "xagosto2022": "",
                            "xsetiembre2022": "",
                            "xoctubre2022": "",
                            "xnoviembre2022": "",
                            "xdiciembre2022": "",
                            "xenero2023": "",
                            "xfebrero2023": "",
                            "xmarzo2023": "",
                            "xabril2023": "",
                            "xmayo2023": "",
                            "xjunio2023": "",
                            "xjulio2023": "",
                            "xagosto2023": "",
                            "xsetiembre2023": "",
                            "xoctubre2023": "",
                            "xnoviembre2023": "",
                            "xdiciembre2023": "",
                            "xenero2024": "",
                            "xfebrero2024": "",
                            "xmarzo2024": "",
                            "xabril2024": "",
                            "xmayo2024": "",
                            "xjunio2024": "",
                            "xjulio2024": "",
                            "xagosto2024": "",
                            "xsetiembre2024": "",
                            "xoctubre2024": "",
                            "xnoviembre2024": "",
                            "xdiciembre2024": "",
                            "ppto2022": "19",
                            "ppto2023": "831",
                            "ppto2024": "40",
                            "children": [
                                {
                                    "key": "1.1.1.1",
                                    "indice": "1.1.1.1",
                                    "nombre": "Actividad 1.1.1.1: Actividades de Gestión Decanal",
                                    "responsable": "DECANO FACULTAD DE INGENIERÍA Y ARQUITECTURA",
                                    "um": "Acción Gestión Decanal",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "16",
                                    "ppto2023": "253",
                                    "ppto2024": "32"
                                },
                                {
                                    "key": "1.1.1.2",
                                    "indice": "1.1.1.2",
                                    "nombre": "Actividad 1.1.1.2: Actividades de planeamiento",
                                    "responsable": "DECANO FACULTAD DE INGENIERÍA Y ARQUITECTURA",
                                    "um": "Acción de Planeamiento",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "1",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "767",
                                    "ppto2023": "1",
                                    "ppto2024": "555"
                                },
                                {
                                    "key": "1.1.1.3",
                                    "indice": "1.1.1.3",
                                    "nombre": "Actividad 1.1.1.3: Actividades de supervisión",
                                    "responsable": "DECANO FACULTAD DE INGENIERÍA Y ARQUITECTURA",
                                    "um": "Acción de Supervisión",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "022",
                                    "ppto2024": "2"
                                },
                                {
                                    "key": "1.1.1.4",
                                    "indice": "1.1.1.4",
                                    "nombre": "Actividad 1.1.1.4: Actividades de grados y títulos",
                                    "responsable": "DECANO FACULTAD DE INGENIERÍA Y ARQUITECTURA",
                                    "um": "Acción de Grados y Títulos",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "767",
                                    "ppto2023": "1",
                                    "ppto2024": "555"
                                },
                                {
                                    "key": "1.1.1.5",
                                    "indice": "1.1.1.5",
                                    "nombre": "Actividad 1.1.1.5: Actividades de registros y estadística",
                                    "responsable": "DECANO FACULTAD DE INGENIERÍA Y ARQUITECTURA",
                                    "um": "Acción de Registros y Estadística",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "022",
                                    "ppto2024": "2"
                                }
                            ]
                        },
                        {
                            "key": "1.1.6",
                            "indice": "1.1.6",
                            "nombre": "Objetivo Específico de Mediano Plazo 1.1.6: Garantizar la capacidad académica de la Escuela de Arquitectura",
                            "responsable": "",
                            "um": "",
                            "meta": "",
                            "enero2022": 10,
                            "febrero2022": 5,
                            "marzo2022": 5,
                            "abril2022": 5,
                            "mayo2022": 5,
                            "junio2022": 5,
                            "julio2022": 6,
                            "agosto2022": 4,
                            "setiembre2022": 5,
                            "octubre2022": 5,
                            "noviembre2022": 0,
                            "diciembre2022": 6,
                            "enero2023": 12,
                            "febrero2023": 6,
                            "marzo2023": 5,
                            "abril2023": 5,
                            "mayo2023": 5,
                            "junio2023": 5,
                            "julio2023": 6,
                            "agosto2023": 5,
                            "setiembre2023": 5,
                            "octubre2023": 5,
                            "noviembre2023": 0,
                            "diciembre2023": 5,
                            "enero2024": 12,
                            "febrero2024": 6,
                            "marzo2024": 5,
                            "abril2024": 5,
                            "mayo2024": 5,
                            "junio2024": 5,
                            "julio2024": 6,
                            "agosto2024": 5,
                            "setiembre2024": 5,
                            "octubre2024": 5,
                            "noviembre2024": 0,
                            "diciembre2024": 5,
                            "xenero2022": "",
                            "xfebrero2022": "",
                            "xmarzo2022": "",
                            "xabril2022": "",
                            "xmayo2022": 3,
                            "xjunio2022": "",
                            "xjulio2022": "",
                            "xagosto2022": "",
                            "xsetiembre2022": "",
                            "xoctubre2022": "",
                            "xnoviembre2022": "",
                            "xdiciembre2022": "",
                            "xenero2023": "",
                            "xfebrero2023": "",
                            "xmarzo2023": "",
                            "xabril2023": "",
                            "xmayo2023": "",
                            "xjunio2023": "",
                            "xjulio2023": "",
                            "xagosto2023": "",
                            "xsetiembre2023": "",
                            "xoctubre2023": "",
                            "xnoviembre2023": "",
                            "xdiciembre2023": "",
                            "xenero2024": "",
                            "xfebrero2024": "",
                            "xmarzo2024": "",
                            "xabril2024": "",
                            "xmayo2024": "",
                            "xjunio2024": "",
                            "xjulio2024": "",
                            "xagosto2024": "",
                            "xsetiembre2024": "",
                            "xoctubre2024": "",
                            "xnoviembre2024": "",
                            "xdiciembre2024": "",
                            "ppto2022": "24",
                            "ppto2023": "445",
                            "ppto2024": "48",
                            "children": [
                                {
                                    "key": "1.1.6.1",
                                    "indice": "1.1.6.1",
                                    "nombre": "Actividad 1.1.6.1: Actividades de completamiento de docentes",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Acción Completam.Docente",
                                    "meta": "9",
                                    "enero2022": 0,
                                    "febrero2022": "1",
                                    "marzo2022": 0,
                                    "abril2022": 0,
                                    "mayo2022": 0,
                                    "junio2022": 0,
                                    "julio2022": "1",
                                    "agosto2022": 0,
                                    "setiembre2022": 0,
                                    "octubre2022": 0,
                                    "noviembre2022": 0,
                                    "diciembre2022": "1",
                                    "enero2023": 0,
                                    "febrero2023": "1",
                                    "marzo2023": 0,
                                    "abril2023": 0,
                                    "mayo2023": 0,
                                    "junio2023": 0,
                                    "julio2023": "1",
                                    "agosto2023": 0,
                                    "setiembre2023": 0,
                                    "octubre2023": 0,
                                    "noviembre2023": 0,
                                    "diciembre2023": "1",
                                    "enero2024": 0,
                                    "febrero2024": "1",
                                    "marzo2024": 0,
                                    "abril2024": 0,
                                    "mayo2024": 0,
                                    "junio2024": 0,
                                    "julio2024": "1",
                                    "agosto2024": 0,
                                    "setiembre2024": 0,
                                    "octubre2024": 0,
                                    "noviembre2024": 0,
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "487",
                                    "ppto2023": "988",
                                    "ppto2024": "1"
                                },
                                {
                                    "key": "1.1.6.2",
                                    "indice": "1.1.6.2",
                                    "nombre": "Actividad 1.1.6.2: Actividades de Control de las actividades académicas",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Acción de control académico",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "948",
                                    "ppto2024": "3"
                                },
                                {
                                    "key": "1.1.6.3",
                                    "indice": "1.1.6.3",
                                    "nombre": "Actividad 1.1.6.3: Actividades de dictado de clases",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Mes de clases dictado",
                                    "meta": "28",
                                    "enero2022": 0,
                                    "febrero2022": 0,
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": 0,
                                    "agosto2022": 0,
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": 0,
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": 0,
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": 0,
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": 0,
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "15",
                                    "ppto2023": "431"
                                },
                                {
                                    "key": "1.1.6.4",
                                    "indice": "1.1.6.4",
                                    "nombre": "Actividad 1.1.6.4: Actividades de dirección",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Acción de Dirección",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "461",
                                    "ppto2024": "2"
                                },
                                {
                                    "key": "1.1.6.5",
                                    "indice": "1.1.6.5",
                                    "nombre": "Actividad 1.1.6.5: Actividades de grados y títulos",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Acción de Grados y Títulos",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "1",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "948",
                                    "ppto2024": "3"
                                },
                                {
                                    "key": "1.1.6.6",
                                    "indice": "1.1.6.6",
                                    "nombre": "Actividad 1.1.6.6: Actividades de registros y estadística",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Acción de Registros y Estadística",
                                    "meta": "36",
                                    "enero2022": "1",
                                    "febrero2022": "1",
                                    "marzo2022": "1",
                                    "abril2022": "1",
                                    "mayo2022": "1",
                                    "junio2022": "1",
                                    "julio2022": "1",
                                    "agosto2022": "1",
                                    "setiembre2022": "1",
                                    "octubre2022": "1",
                                    "noviembre2022": "1",
                                    "diciembre2022": "1",
                                    "enero2023": "1",
                                    "febrero2023": "1",
                                    "marzo2023": "1",
                                    "abril2023": "1",
                                    "mayo2023": "1",
                                    "junio2023": "1",
                                    "julio2023": "1",
                                    "agosto2023": "1",
                                    "setiembre2023": "1",
                                    "octubre2023": "1",
                                    "noviembre2023": "1",
                                    "diciembre2023": "1",
                                    "enero2024": "1",
                                    "febrero2024": "1",
                                    "marzo2024": "1",
                                    "abril2024": "1",
                                    "mayo2024": "1",
                                    "junio2024": "1",
                                    "julio2024": "1",
                                    "agosto2024": "1",
                                    "setiembre2024": "1",
                                    "octubre2024": "1",
                                    "noviembre2024": "1",
                                    "diciembre2024": "1",
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "461",
                                    "ppto2024": "2"
                                },
                                {
                                    "key": "1.1.6.7",
                                    "indice": "1.1.6.7",
                                    "nombre": "Actividad 1.1.6.7: Actividades de desarrollo curricular",
                                    "responsable": "DIRECTOR ESCUELA",
                                    "um": "Verificación efectividad de currícula",
                                    "meta": "6",
                                    "enero2022": "1",
                                    "febrero2022": 0,
                                    "marzo2022": 0,
                                    "abril2022": 0,
                                    "mayo2022": 0,
                                    "junio2022": 0,
                                    "julio2022": "1",
                                    "agosto2022": 0,
                                    "setiembre2022": 0,
                                    "octubre2022": 0,
                                    "noviembre2022": 0,
                                    "diciembre2022": 0,
                                    "enero2023": "1",
                                    "febrero2023": 0,
                                    "marzo2023": 0,
                                    "abril2023": 0,
                                    "mayo2023": 0,
                                    "junio2023": 0,
                                    "julio2023": "1",
                                    "agosto2023": 0,
                                    "setiembre2023": 0,
                                    "octubre2023": 0,
                                    "noviembre2023": 0,
                                    "diciembre2023": 0,
                                    "enero2024": "1",
                                    "febrero2024": 0,
                                    "marzo2024": 0,
                                    "abril2024": 0,
                                    "mayo2024": 0,
                                    "junio2024": 0,
                                    "julio2024": "1",
                                    "agosto2024": 0,
                                    "setiembre2024": 0,
                                    "octubre2024": 0,
                                    "noviembre2024": 0,
                                    "diciembre2024": 0,
                                    "xenero2022": "",
                                    "xfebrero2022": "",
                                    "xmarzo2022": "",
                                    "xabril2022": "",
                                    "xmayo2022": "0",
                                    "xjunio2022": "",
                                    "xjulio2022": "",
                                    "xagosto2022": "",
                                    "xsetiembre2022": "",
                                    "xoctubre2022": "",
                                    "xnoviembre2022": "",
                                    "xdiciembre2022": "",
                                    "xenero2023": "",
                                    "xfebrero2023": "",
                                    "xmarzo2023": "",
                                    "xabril2023": "",
                                    "xmayo2023": "",
                                    "xjunio2023": "",
                                    "xjulio2023": "",
                                    "xagosto2023": "",
                                    "xsetiembre2023": "",
                                    "xoctubre2023": "",
                                    "xnoviembre2023": "",
                                    "xdiciembre2023": "",
                                    "xenero2024": "",
                                    "xfebrero2024": "",
                                    "xmarzo2024": "",
                                    "xabril2024": "",
                                    "xmayo2024": "",
                                    "xjunio2024": "",
                                    "xjulio2024": "",
                                    "xagosto2024": "",
                                    "xsetiembre2024": "",
                                    "xoctubre2024": "",
                                    "xnoviembre2024": "",
                                    "xdiciembre2024": "",
                                    "ppto2022": "1",
                                    "ppto2023": "709",
                                    "ppto2024": "3"
                                }
                            ]
                        }
                    ]
                },
            ]
        },

    ]
    // Data.map((item, index) => {
    //     console.log(item)
    //     console.log(index)
    //
    //     item._id = index;
    //     db.put(item)
    // })

    console.log('TREE CALC')
    // for (let i=0; i<NewData.length; i++) {
    //     TreeCalc(NewData[i]);
    // }


    useEffect(() => {
        // TreeCalc2(NewData[0])
        // TreeCalc2(NewData[1])
        // TreeCalc2(NewData[2])
        // TreeCalc2(NewData[3])
        // @ts-ignore
        setData(NewData);
    }, [])
    // console.log('DATA')
    // console.log(data)

    const showDrawer = () => {
        setVisible(true);
    }

    const onClose = () => {
        setVisible(false);
    }


    return (
        <div className={style.component}>
            <div className={style.title}>
                Plan Operativo Institucional
            </div>
            <div className={style.container}>
                <Table handleCellClick={showDrawer} data={data}/>
                <Drawer placement="right" onClose={onClose} visible={visible} closeIcon={null}>
                    <Card
                        style={{width: 330, marginBottom: '20px'}}
                        cover={
                            <img
                                alt="example"
                                src="https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png"
                            />
                        }
                        actions={[
                            <SettingOutlined key="setting"/>,
                            <EditOutlined key="edit"/>,
                            <EllipsisOutlined key="ellipsis"/>,
                        ]}
                    >
                        <Meta
                            avatar={<Avatar src="https://joeschmoe.io/api/v1/random"/>}
                            title="Documento 1"
                            description="Este es un documento"
                        />
                    </Card>

                    <Card
                        style={{width: 330, marginBottom: '20px'}}
                        cover={
                            <img
                                alt="example"
                                src="https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png"
                            />
                        }
                        actions={[
                            <SettingOutlined key="setting"/>,
                            <EditOutlined key="edit"/>,
                            <EllipsisOutlined key="ellipsis"/>,
                        ]}
                    >
                        <Meta
                            avatar={<Avatar src="https://joeschmoe.io/api/v1/random"/>}
                            title="Documento 2"
                            description="Este es un documento"
                        />
                    </Card>

                    <Card
                        style={{width: 330, marginBottom: '20px'}}
                        cover={
                            <img
                                alt="example"
                                src="https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png"
                            />
                        }
                        actions={[
                            <SettingOutlined key="setting"/>,
                            <EditOutlined key="edit"/>,
                            <EllipsisOutlined key="ellipsis"/>,
                        ]}
                    >
                        <Meta
                            avatar={<Avatar src="https://joeschmoe.io/api/v1/random"/>}
                            title="Documento 3"
                            description="Este es un documento"
                        />
                    </Card>
                </Drawer>
            </div>
        </div>
    )
}

export default Component
